#!/usr/bin/env node
// Feed table generator (WK-08, ARCH-13, 29 Sep 2026).
//
// src/jurisdictions.json is the single source of the configured feed list.
// The feed tables in the root README.md, the root STATUS.md and this
// Worker's README.md are generated from it, between the markers
//   <!-- feeds-table:start ... -->  and  <!-- feeds-table:end -->
// so no document can claim a different feed count from the code.
//
//   node scripts/feeds-table.mjs           print the table
//   node scripts/feeds-table.mjs --write   rewrite the table in every document
//   node scripts/feeds-table.mjs --check   exit 1 if any document disagrees
//
// tests/feeds-table.test.mjs calls checkDoc() on the real documents, and on
// seeded bad specimens as a canary.

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
export const WORKER_DIR = resolve(HERE, "..");
export const REPO_ROOT = resolve(WORKER_DIR, "..", "..");
export const CONFIG_PATH = resolve(WORKER_DIR, "src", "jurisdictions.json");
export const DOC_PATHS = [
  resolve(REPO_ROOT, "README.md"),
  resolve(REPO_ROOT, "STATUS.md"),
  resolve(WORKER_DIR, "README.md"),
];

export const START_PREFIX = "<!-- feeds-table:start";
export const START_MARKER =
  "<!-- feeds-table:start (generated by workers/aph-proxy/scripts/feeds-table.mjs from src/jurisdictions.json; do not edit by hand) -->";
export const END_MARKER = "<!-- feeds-table:end -->";

export function loadConfig(path = CONFIG_PATH) {
  return JSON.parse(readFileSync(path, "utf8"));
}

function cell(s) {
  return String(s).replace(/\|/g, "\\|");
}

/** The generated block body (without markers) for one jurisdiction. */
export function renderFeedsTable(config, jurisdiction = "aph") {
  const j = config[jurisdiction];
  if (!j || !Array.isArray(j.feeds)) throw new Error(`jurisdictions.json: no feeds for "${jurisdiction}"`);
  const hours = (m) => (m % 60 === 0 ? `${m / 60} hours` : `${m} minutes`);
  const cadence = j.feeds
    .filter((f) => f.pollEveryMinutes !== undefined || f.blockedBackoffMinutes !== undefined)
    .map((f) => {
      const parts = [];
      if (f.pollEveryMinutes !== undefined) parts.push(`at most every ${hours(f.pollEveryMinutes)}`);
      if (f.blockedBackoffMinutes !== undefined) {
        parts.push(`every ${hours(f.blockedBackoffMinutes)} after the host refuses the Worker (reported as source blocked)`);
      }
      return `${cell(f.label)}: ${parts.join("; ")}.`;
    });
  const lines = [
    `${j.feeds.length} configured feeds (${j.label}), polled every 30 minutes by the \`*/30\` cron.`,
    ...(cadence.length ? ["", "Feeds with their own cadence (0.16.11):", "", ...cadence.map((c) => `- ${c}`)] : []),
    "",
    "| # | Feed label | Kind | URL |",
    "|---|---|---|---|",
    ...j.feeds.map((f, i) => `| ${i + 1} | ${cell(f.label)} | ${cell(f.kind)} | \`${cell(f.url)}\` |`),
  ];
  return lines.join("\n");
}

/** Returns the text between the markers, or null when a marker is missing. */
export function extractBlock(text) {
  const s = text.indexOf(START_PREFIX);
  if (s === -1) return null;
  const startEnd = text.indexOf("-->", s);
  const e = text.indexOf(END_MARKER, startEnd);
  if (startEnd === -1 || e === -1) return null;
  return text.slice(startEnd + 3, e).replace(/\r\n/g, "\n").trim();
}

/** Verdict: { ok, problems[] } for one document against the config. */
export function checkDoc(text, config, name = "document") {
  const problems = [];
  const block = extractBlock(text);
  if (block === null) {
    problems.push(`${name}: feeds-table markers missing`);
    return { ok: false, problems };
  }
  const expected = renderFeedsTable(config);
  if (block !== expected) problems.push(`${name}: feed table differs from src/jurisdictions.json`);
  if (text.split(START_PREFIX).length - 1 > 1) problems.push(`${name}: more than one feeds-table block`);
  return { ok: problems.length === 0, problems };
}

export function replaceBlock(text, config) {
  const s = text.indexOf(START_PREFIX);
  const e = text.indexOf(END_MARKER, s);
  if (s === -1 || e === -1) throw new Error("feeds-table markers missing");
  return `${text.slice(0, s)}${START_MARKER}\n${renderFeedsTable(config)}\n${text.slice(e)}`;
}

const isMain = process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const config = loadConfig();
  const mode = process.argv[2];
  if (mode === "--write") {
    for (const p of DOC_PATHS) {
      const before = readFileSync(p, "utf8");
      const after = replaceBlock(before, config);
      if (after !== before) writeFileSync(p, after);
      console.log(`${after === before ? "unchanged" : "updated"}: ${p}`);
    }
  } else if (mode === "--check") {
    const problems = DOC_PATHS.flatMap((p) => checkDoc(readFileSync(p, "utf8"), config, p).problems);
    if (problems.length) {
      for (const pr of problems) console.error(pr);
      process.exit(1);
    }
    console.log(`feed tables agree with src/jurisdictions.json in ${DOC_PATHS.length} documents`);
  } else {
    console.log(renderFeedsTable(config));
  }
}
